[SQUASHME] ASoC: SOF: intel: hda-dai: add include file
Detected with Sparse, variables need to be static if not declared

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Signed-off-by: Samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>

[SQUASHME] ASoC: SOF: intel: fix a typo in hda-dai

Should be 8 channel for SSP2 Rx, correct it.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>

[SQUASHME] ASoC: Intel: fix Kconfig typos

Fix ASoC: Intel: select relevant machine drivers for SOF
s/INTEL_SKL/INTEL_SKYLAKE

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

[SQUASHME] ASoC: SOF: add mm.h

0-day complains that on some architectures such as m68k mm_struct is not
defined. Make sure it's added.

In file included from ./arch/m68k/include/asm/pgtable_mm.h:148,
                 from ./arch/m68k/include/asm/pgtable.h:5,
                 from sound/soc/sof/pm.c:15:
./arch/m68k/include/asm/motorola_pgtable.h: In function 'pgd_offset':
./arch/m68k/include/asm/motorola_pgtable.h:199:11: error: dereferencing pointer to incomplete type 'const struct mm_struct'
  return mm->pgd + pgd_index(address);
           ^~
In file included from ./arch/m68k/include/asm/pgtable_mm.h:148,
                 from ./arch/m68k/include/asm/pgtable.h:5,
                 from sound/soc/sof/core.c:15:
./arch/m68k/include/asm/motorola_pgtable.h: In function 'pgd_offset':
./arch/m68k/include/asm/motorola_pgtable.h:199:11: error: dereferencing pointer to incomplete type 'const struct mm_struct'
  return mm->pgd + pgd_index(address);

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit 0fee76c9ff8cfcdb89bf5967cf14b7dd44a0e15f)

[SQUASHME] ASoC: SOF: ops: fix uninitialized use warning

For some architectures/compilers, 0-day reports errors

sound/soc/sof/ops.c: In function 'snd_sof_pci_update_bits_unlocked':
sound/soc/sof/ops.c:26:6: warning: 'ret' is used uninitialized in this function [-Wuninitialized]
  u32 ret;
      ^~~

Fix by forcing value to ~0 (as done in pci_read_config_dword)

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit 28fc73b252eaa6438e9c10a854f7067db24f07cd)

[SQUASHME] ASoC: sof: core: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit ad83ac7e64cf4d396c3f3c59618160ed8f8cce5d)

[SQUASHME] ASoC: sof: pcm: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 73eb318245f81d76bbf9fed30aec00a8c78c2ce5)

[SQUASHME] ASoC: sof: loader: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 81063c85e9ed7f63175547607572dfc6094e5eaa)

[SQUASHME] ASoC: sof: ipc: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit dc9bfad004772168c81a8cdb1b178c813d6a8119)

[SQUASHME] ASoC: sof: ops: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 621a20389a496720ce1193eff6f00b172a5481e0)

[SQUASHME] ASoC: sof: skl, cnl, apl: cleanup - add comments and reorder funcs

Add comments describing funcs/code blocks and reorder funcs so features
are grouped.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit cb84cdb5a892b05bc2db12fc57740a319a535115)

[SQUASH] ASoC: SOF: Kconfig: cleanup Kconfig debug options

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit b66e8ef1122d04210a1829c9245b0e1d7b37b5bc)

[SQUASHME] ASoC: SOF: core fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 94001aa81cf3f921a689e4b557fb487c1943dd3c)

[SQUASHME] ASoC: SOF: debug: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit d6c73564cffbc3ad7885e933e6fcc5734142e099)

[SQUASHME] ASoC: SOF: ipc: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 798b7aabf7a170d608c812e7b548ed46e3295b68)

[SQUASHME] ASoC: SOF: topology: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 3fbc96aaceceffd226200b3c4ba85ca89a6e7e06)

[SQUASHME] ASoC: SOF: trace: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit c023b55fdc08efc8e4e7f88d2265edff44ea4a0f)

[SQUASHME] ASoC: SOF: pcm: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit c764884be50142fd585965070e930f7a7181f26e)

[SQUASHME] ASoC: SOF: hda: fix sparse warnings.

Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
(cherry picked from commit 7de8df0d32687fb0a9765c44711643a1de4e0fd7)

[SQUASHME]ASoC: SOF: cleanup for pci probing.

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
(cherry picked from commit 67675cb51a29de649934df0da7c735e7139ac11f)

[SQUASHME]ASoC: SOF: utils: fix memory leak of names during remove()

Change to use devm_kstrdup() for string duplicate allocation, which will
be freed together with dev free, to fix memory leak (names are not freed)
during remove().

Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
Signed-off-by: Samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>
(cherry picked from commit 0e60d1c5ce6b54cdafbf230a256d87baceea304a)

Conflicts:
	sound/soc/sof/sof-priv.h
	struct snd_sof_dfsentry_io to be used instead of struct snd_sof_dfsentry

Change-Id: Ic881037ffec5520342968465b26a90434897eec6